# General settings
# ---------------------------------------------------------------------------------------

# Language of your content in 2-letter code, e.g.: en, de.
# You may also provide a location, e.g.: en-us, de_AT.
lang:                  en

# The title of your blog. Used in the sidebar and the browser tab.
title:                 Starter Kit

# A short description (~150 chars) of the page used for the meta description tag.
# Can use markdown, but no more than one paragraph (enforced by `>`)
description:           >
  Hydejack is a boutique Jekyll theme for hackers, nerds, and academics,
  with a focus on personal sites that are meant to impress.

# A shorter description for the sidebar.
tagline:               Change `tagline` in `_config.yml`

# A list of keywords for your blog
keywords:              []

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/img/logo.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  # Used by `jekyll-feed`:
  name:                <firstname> <lastname>
  email:               <mail@domain.tld>
  # # Used by `jekyll-seo-tag`:
  # twitter:             <username>

# Add links to the sidebar.
menu:
  - title:             Example
    url:               /example/
  - title:             Documentation
    url:               /docs/
  - title:             About
    url:               /about/

# Add links to the footer.
# Typically you'll want to link to your cookie- or privacy policy (if appliable), etc..
legal:
  - title:             LICENSE
    url:               /LICENSE/
  - title:             NOTICE
    url:               /NOTICE/
  - title:             CHANGELOG
    url:               /CHANGELOG/

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2024. All rights reserved.

# Format of the permalinks
permalink:             /:categories/:year-:month-:day-:title/

# Pagination configuration (used by the `blog` layout)
paginate:              10
paginate_path:         /:num/
----------------------------------------
jekyll_compose:
  default_front_matter:
    drafts:
      layout: post
      description: > 
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
    posts:
      layout: post
      description: > 
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
    projects:
      layout: project
      description: > 
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
      links:
        - title: Project Link
          url: https://example.com
